// Class XII · Part A — Introductory Macroeconomics: Data Lab / Concept
// Explorer content that was completely missing before this integration
// pass (Unit 1 Methods of Calculating National Income & Basic Concepts,
// Unit 3 Propensity to Consume & Save). See CLAUDE.md for the data
// contract.

if (typeof SIMS !== 'undefined') {
    SIMS.push(
        {
            id: 'macro-national-income-methods',
            module: 'macro',
            title: 'National Income: Value Added, Income & Expenditure Methods',
            desc: 'Enter each firm\'s output, intermediate consumption and factor payments — see GDP computed by the Value Added and Income methods, and verify they agree.',
            class: 'XII', part: 'A', unit: 1, unitTitle: 'National Income and Related Aggregates', topicLabel: 'Methods of Calculating National Income',
            syllabusIds: ['XII-A-U1-METHODS', 'XII-A-U1-AGGREGATES'],
            mode: 'datalab',
            concept: '<p>National income can be measured three ways, and — measured correctly — all three give the <b>same total</b>, because they trace the same flow of production, income and spending around the economy. The <b>Value Added Method</b> sums each firm\'s Value of Output minus what it bought from other firms (Intermediate Consumption), avoiding double-counting. The <b>Income Method</b> sums the factor incomes (Wages + Rent + Interest + Profit) generated by that same production — Profit is what is left over after paying the other three factors, so the Income Method total is <i>guaranteed</i> to equal the Value Added total. The <b>Expenditure Method</b> (C + I + G + X−M) reaches the same total from the spending side; here it is shown as an illustrative split of that same GDP figure rather than a separately entered dataset, since Expenditure-side data isn\'t naturally per-firm.</p>',
            formulas: ['Value Added Method: GDP = Σ (Value of Output − Intermediate Consumption)', 'Income Method: GDP = Σ (Wages + Rent + Interest + Profit)', 'Profit (residual) = Value Added − Wages − Rent − Interest', 'Expenditure Method: GDP = C + I + G + (X − M)'],
            dataLab: {
                columns: [
                    { id: 'firm', label: 'Firm / Sector', type: 'text', default: 'Firm' },
                    { id: 'output', label: 'Value of Output', type: 'number', step: 5, min: 0, default: 100 },
                    { id: 'ic', label: 'Intermediate Consumption', type: 'number', step: 5, min: 0, default: 40 },
                    { id: 'wages', label: 'Wages Paid', type: 'number', step: 5, min: 0, default: 30 },
                    { id: 'rent', label: 'Rent Paid', type: 'number', step: 5, min: 0, default: 5 },
                    { id: 'interest', label: 'Interest Paid', type: 'number', step: 5, min: 0, default: 5 }
                ],
                minRows: 2,
                maxRows: 8,
                addRowDefault: { firm: 'New Firm', output: 100, ic: 40, wages: 30, rent: 5, interest: 5 },
                defaultRows: [
                    { firm: 'Farmer (wheat)', output: 100, ic: 0, wages: 20, rent: 10, interest: 5 },
                    { firm: 'Flour Mill', output: 160, ic: 100, wages: 25, rent: 5, interest: 5 },
                    { firm: 'Bakery', output: 260, ic: 160, wages: 40, rent: 10, interest: 10 }
                ],
                calculate(rows) {
                    let GDP_VA = 0, totalWages = 0, totalRent = 0, totalInterest = 0, totalProfit = 0;
                    rows.forEach(r => {
                        const valueAdded = r.output - r.ic;
                        const profit = valueAdded - r.wages - r.rent - r.interest;
                        GDP_VA += valueAdded;
                        totalWages += r.wages; totalRent += r.rent; totalInterest += r.interest; totalProfit += profit;
                    });
                    const GDP_Income = totalWages + totalRent + totalInterest + totalProfit;
                    const C = 0.6 * GDP_VA, I = 0.2 * GDP_VA, G = 0.15 * GDP_VA, NX = 0.05 * GDP_VA;

                    return {
                        traces: [
                            { x: ['Value Added Method', 'Income Method', 'Expenditure Method\n(illustrative split)'], y: [GDP_VA, GDP_Income, C + I + G + NX], type: 'bar', marker: { color: ['#2563eb', '#10b981', '#f59e0b'] } }
                        ],
                        layout: { xaxis: { title: 'Method' }, yaxis: { title: 'National Income (GDP)' }, showlegend: false },
                        stats: [
                            { label: 'GDP — Value Added Method', value: fmt(GDP_VA, 0) },
                            { label: 'GDP — Income Method', value: fmt(GDP_Income, 0) },
                            { label: 'Implied Total Profit', value: fmt(totalProfit, 0) },
                            { label: 'GDP — Expenditure (C+I+G+NX, illustrative split)', value: fmt(C + I + G + NX, 0) }
                        ],
                        metrics: { GDP_VA, GDP_Income, diff: Math.abs(GDP_VA - GDP_Income) },
                        interpretation: `Value Added (₹${fmt(GDP_VA, 0)}) and Income Method (₹${fmt(GDP_Income, 0)}) match exactly — they must, because Profit is defined as whatever value-added is left after paying Wages, Rent and Interest. ${totalProfit < 0 ? 'Note: implied Profit is negative for the economy as a whole — the wages/rent/interest you entered exceed the value added, i.e. these firms are running a collective loss.' : ''} The Expenditure split shown is illustrative (fixed 60/20/15/5% shares of the same total), since C/I/G/NX aren't naturally per-firm figures.`
                    };
                }
            },
            practice: [
                { prompt: 'Raise one firm\'s Wages without changing its Value of Output. What happens to that firm\'s implied Profit?', hint: 'It falls — Profit is a residual (Value Added − Wages − Rent − Interest), so paying more to labour leaves less for profit, with total GDP unchanged.' },
                { prompt: 'Raise the Flour Mill\'s Intermediate Consumption to match its Value of Output. What happens to its Value Added?', hint: 'It falls to zero — if a firm buys as much from other firms as it sells, it has added no new value itself.' }
            ],
            challenge: {
                prompt: 'Edit the data so total GDP (by either method — they always match) exceeds ₹400.',
                check(state, metrics) { return metrics && metrics.GDP_VA > 400; }
            }
        },
        {
            id: 'macro-basic-concepts',
            module: 'macro',
            title: 'Basic Macroeconomic Concepts',
            desc: 'Classify goods as consumption/capital and final/intermediate, and variables as stock/flow.',
            class: 'XII', part: 'A', unit: 1, unitTitle: 'National Income and Related Aggregates', topicLabel: 'Consumption/Capital, Final/Intermediate Goods, Stock/Flow, Depreciation',
            syllabusIds: ['XII-A-U1-BASIC-CONCEPTS'],
            mode: 'explorer',
            concept: '<p>Before computing national income, a few basic classifications need to be second-nature. Is a good bought for immediate use (a <b>consumption good</b>) or to produce other things (a <b>capital good</b>)? Is it used up within the year of production (an <b>intermediate good</b>, excluded from GDP to avoid double-counting) or does it leave the production boundary for final use (a <b>final good</b>, included in GDP)? Is a variable measured at a point in time (a <b>stock</b>) or over a period of time (a <b>flow</b>)? Classify each item below.</p>',
            formulas: ['Net Investment = Gross Investment − Depreciation', 'GDP counts only Final Goods, to avoid double-counting Intermediate Goods'],
            explorer: {
                type: 'cards',
                cards: [
                    { prompt: 'A car bought by a taxi driver to run a taxi business', options: ['Consumption Good', 'Capital Good'], correctIndex: 1, explain: 'Capital Good — it is used as a means of further production (earning fares), not consumed for its own sake.' },
                    { prompt: 'Bread bought by a household to eat', options: ['Consumption Good', 'Capital Good'], correctIndex: 0, explain: 'Consumption Good — bought for direct, final personal use.' },
                    { prompt: 'Steel bought by a car company to build cars', options: ['Final Good', 'Intermediate Good'], correctIndex: 1, explain: "Intermediate Good — it is used up within the same year to produce another good, so counting it separately would double-count it inside the car's price." },
                    { prompt: 'A car bought by a household for personal use', options: ['Final Good', 'Intermediate Good'], correctIndex: 0, explain: 'Final Good — it leaves the production boundary for end use and is counted once, in full, in GDP.' },
                    { prompt: "India's GDP for the year 2024–25", options: ['Stock', 'Flow'], correctIndex: 1, explain: 'Flow — GDP is measured over a period of time (a year), like income or investment.' },
                    { prompt: "A firm's total capital stock as on 31 March 2025", options: ['Stock', 'Flow'], correctIndex: 0, explain: 'Stock — measured at one point in time, like wealth or capital.' },
                    { prompt: 'Gross Investment minus Depreciation equals…', options: ['Net Investment', 'Total Consumption'], correctIndex: 0, explain: 'Net Investment — Depreciation is the wear-and-tear of existing capital; subtracting it from Gross Investment leaves only the genuinely new addition to capital stock.' },
                    { prompt: 'Depreciation is best described as…', options: ['Wear and tear (consumption) of fixed capital', 'A type of household consumption good'], correctIndex: 0, explain: "Depreciation is the fall in the value of fixed capital due to wear and tear and obsolescence — it's why GDP is 'Gross' and NDP is 'Net' of it." }
                ]
            },
            practice: [
                { prompt: 'Name one good that could be either a consumption good or a capital good, depending on who buys it.', hint: 'A car is the classic example — a consumption good for a household, a capital good for a taxi/delivery business.' }
            ]
        },
        {
            id: 'macro-propensity',
            module: 'macro',
            title: 'Propensity to Consume & Save (APC, MPC, APS, MPS)',
            desc: 'Enter Income/Consumption data across periods and see APC, MPC, APS, MPS and the break-even income calculated live.',
            class: 'XII', part: 'A', unit: 3, unitTitle: 'Determination of Income and Employment', topicLabel: 'Propensity to Consume & Save',
            syllabusIds: ['XII-A-U3-PROPENSITY'],
            mode: 'datalab',
            concept: '<p><b>Average Propensity to Consume (APC)</b> = Consumption / Income for a given period. <b>Marginal Propensity to Consume (MPC)</b> = the change in Consumption per extra rupee of Income — the slope of the consumption line across periods. <b>APS</b> and <b>MPS</b> are the saving-side mirror images (APC+APS=1, MPC+MPS=1). The <b>break-even income</b> is where Consumption exactly equals Income (saving is zero). Edit the Income/Consumption table for each period and every measure recalculates.</p>',
            formulas: ['APC = C / Y', 'MPC = ΔC / ΔY (fitted slope across periods)', 'APS = 1 − APC', 'MPS = 1 − MPC', 'Break-even Income: Y₀ = Autonomous Consumption / (1 − MPC)'],
            dataLab: {
                columns: [
                    { id: 'period', label: 'Period', type: 'text', default: 'Year' },
                    { id: 'y', label: 'Income (Y)', type: 'number', step: 10, min: 0, default: 100 },
                    { id: 'c', label: 'Consumption (C)', type: 'number', step: 10, min: 0, default: 100 }
                ],
                minRows: 3,
                maxRows: 10,
                addRowDefault: { period: 'Year', y: 300, c: 250 },
                defaultRows: [
                    { period: 'Year 1', y: 100, c: 110 }, { period: 'Year 2', y: 150, c: 145 },
                    { period: 'Year 3', y: 200, c: 180 }, { period: 'Year 4', y: 250, c: 215 },
                    { period: 'Year 5', y: 300, c: 250 }, { period: 'Year 6', y: 350, c: 285 }
                ],
                calculate(rows) {
                    const n = rows.length;
                    const ys = rows.map(r => r.y), cs = rows.map(r => r.c);
                    const ybar = ys.reduce((s, y) => s + y, 0) / n;
                    const cbar = cs.reduce((s, c) => s + c, 0) / n;
                    let num = 0, den = 0;
                    for (let i = 0; i < n; i++) { num += (ys[i] - ybar) * (cs[i] - cbar); den += (ys[i] - ybar) ** 2; }
                    const MPC = den === 0 ? 0 : num / den;
                    const a = cbar - MPC * ybar; // autonomous consumption (fitted intercept)
                    const MPS = 1 - MPC;
                    const lastY = ys[ys.length - 1], lastC = cs[cs.length - 1];
                    const APC = lastY > 0 ? lastC / lastY : 0;
                    const APS = 1 - APC;
                    const breakEven = (1 - MPC) !== 0 ? a / (1 - MPC) : NaN;

                    const yMax = Math.max(...ys) * 1.3;
                    const lineXs = range(21).map(i => (i / 20) * yMax);
                    return {
                        traces: [
                            { x: ys, y: cs, mode: 'markers', name: 'Data (Y, C)', marker: { color: '#2563eb', size: 9 } },
                            { x: lineXs, y: lineXs.map(y => a + MPC * y), mode: 'lines', name: 'Fitted Consumption Line', line: { color: '#10b981', width: 2 } },
                            { x: lineXs, y: lineXs, mode: 'lines', name: '45° Line (C = Y)', line: { color: '#9ca3af', dash: 'dot', width: 2 } }
                        ],
                        layout: { xaxis: { title: 'Income (Y)' }, yaxis: { title: 'Consumption (C)' } },
                        stats: [
                            { label: 'MPC (fitted slope)', value: fmt(MPC) },
                            { label: 'MPS', value: fmt(MPS) },
                            { label: 'APC (latest period)', value: fmt(APC) },
                            { label: 'APS (latest period)', value: fmt(APS) },
                            { label: 'Break-even Income', value: isFinite(breakEven) ? fmt(breakEven, 0) : '—' }
                        ],
                        metrics: { MPC, MPS, APC, APS, breakEven },
                        interpretation: `MPC + MPS = ${fmt(MPC + MPS)} (always 1, by definition). ${APC > 1 ? 'APC exceeds 1 in the latest period — the household is dissaving (spending more than its income).' : `At the break-even income of ${isFinite(breakEven) ? fmt(breakEven, 0) : '—'}, saving is exactly zero — below it households dissave, above it they save.`}`
                    };
                }
            },
            practice: [
                { prompt: 'Edit one row so Consumption exceeds Income for that period. What does APS become?', hint: 'Negative — spending more than income means negative saving (dissaving) for that period.' },
                { prompt: 'Make Consumption rise in exact lockstep with Income (ΔC = ΔY every period). What does MPC become?', hint: 'MPC = 1 — every extra rupee of income is spent, none saved.' }
            ],
            challenge: {
                prompt: 'Edit the data so MPC exceeds 0.9 (people save very little of each extra rupee).',
                check(state, metrics) { return metrics && metrics.MPC > 0.9; }
            }
        }
    );
}
